# Generated by Django 5.1.7 on 2025-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('generation', models.CharField(default='', max_length=4)),
                ('Vram_amount', models.CharField(default='', max_length=20)),
                ('release_date', models.DateField(default='', max_length=20)),
                ('price', models.IntegerField(default='')),
            ],
        ),
    ]
