# Generated by Django 5.1.7 on 2025-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='Vram_amount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='generation',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='gpu',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='release_date',
            field=models.DateField(default='', max_length=20),
        ),
    ]
