# Generated by Django 5.1.7 on 2025-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gpu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
