# Generated by Django 5.1.7 on 2025-03-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gpu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
