# Generated by Django 5.1.7 on 2025-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_release_date_gpu_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='release_year',
            field=models.IntegerField(default=''),
        ),
    ]
