# Generated by Django 5.1.7 on 2025-03-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gpu_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='price',
            new_name='price_USD',
        ),
    ]
