# Generated by Django 5.1.7 on 2025-03-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_price_gpu_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='Vram_amount',
            new_name='Vram_amount_GB',
        ),
    ]
