# Generated by Django 5.1.7 on 2025-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_vram_amount_gpu_vram_amount_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='graphics_processor',
            field=models.CharField(default='', max_length=10),
        ),
    ]
